### PR TITLE
add RESTORE_ON_BACKUP env var option

### PR DESCRIPTION
**Pull request by krezreb**
added this option to be able to ship changes to s3 at runtime and have them pulled to the docker volume

### CODE REVIEW

**Comment by hongkongkiwi** [comment]
Can you merge this?

**Comment by krezreb** [comment]
> Can you merge this?

Me?  No I can't :(

**Comment by fabiob** [comment]
I'm not confident about merging this PR, as it adds a whole new use case to the project.

The original idea was to consider the local files as the authoritative source of the files, and S3 as just a backup. The S3 volume would only be read when the local directory was empty (or when asking it to force a restore, in which case it would overwrite all local files).

This new flag would merge the contents on S3 with the contents of the local volume before each backup. This adds a lot of complexity and raises a lot of questions: what about deleted files? what if a file is modified both on S3 and on the local volume?

I'm not sure this small project is ready to include that amount of complexity. So, I would recommend a fork.

**Comment by hongkongkiwi** [comment]
In my usecase I don’t need to worry about merging, I just want S3 to be the authorities source and replace the local files with the S3 version. The local volume would be ready only.

**Pull request closed without merging**
